### ISSUE TITLE
Add addons list

### ISSUE THREAD

**Issue by tomkukral** [Mirantis/kqueen#67]
We will list services, filter it according to annotations and display in grid.

```
kind: Service
apiVersion: v1
metadata:
  name: monocular
  annotations:
    kqueen/name: Monocular
    kqueen/icon: https://www.modarmory.com/wp-content/uploads/2014/05/night-vision-monocular-icon.png
    kqueen/link: http://monocular-load-balancer-or-ingress-url
spec:
  selector:
    app: MyApp
  ports:
  - protocol: TCP
    port: 80
    targetPort: 9376
```
